"""Workspace initialization -- creates workspace folder structure on project creation."""

from pathlib import Path

from app.workspace.storage import workspace_storage
from app.workspace.skill_router import clear_cache


DEFAULT_SKILLS_DIR = Path(__file__).parent / "default_skills"


async def init_workspace(project_id: str, project_name: str = "", description: str = ""):
    """Initialize a workspace for a new project.

    Creates:
    - README.md with project summary
    - skills/ with default skill files
    - knowledge/ (empty, populated by sync_knowledge)
    - references/ (empty, populated by user/team)
    """
    # README
    readme = f"""# {project_name or 'Project'}

{description or 'No description yet.'}

## Workspace Structure
- `skills/` -- AI skill files that define how the agent handles different tasks
- `knowledge/` -- Auto-synced project data (commits, deploys, metrics)
- `references/` -- Reference templates and examples (add your own here)

## How Skills Work
Each skill file defines:
- What triggers it (keywords in user requests)
- What tools the agent can use
- Rules and patterns to follow
- Output format

The agent automatically selects the right skill based on your request.
"""
    await workspace_storage.write_file(project_id, "README.md", readme)

    # Copy default skills
    for md_file in sorted(DEFAULT_SKILLS_DIR.glob("*.md")):
        content = md_file.read_text(encoding="utf-8")
        await workspace_storage.write_file(project_id, f"skills/{md_file.name}", content)

    # Create empty placeholder files for knowledge and references
    await workspace_storage.write_file(
        project_id, "knowledge/.gitkeep",
        "# Knowledge files are auto-generated by the sync task every 6 hours.\n"
    )
    await workspace_storage.write_file(
        project_id, "references/.gitkeep",
        "# Add your reference templates here. The agent will use them when generating content.\n"
    )

    # Clear cache so next agent run picks up the new workspace
    clear_cache(project_id)
